sudo: false
language: perl
perl:
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
cache:
  directories:
    - local

install:
  - which carton || cpanm --notest Carton
  - which minil || cpanm --notest Minilla
  - carton install

script:
  - minil test
